graph TD
A[UserInteractionHandler] -->|Has a| B[Level]
B -->|Has a| C[Player]
C -->|Has a| J[GameObject]
B -->|Has a| F[HUD]
B -->|Has a| G[GameArea]
G --> |Has many| H[GameObject]
F --> |Has a| C[Player]
I[LevelLoader] --> |Produce| B
