graph TD
A(Player Interaction) ==>|Depends on| B(Game Engine)
B ==>|Depends on| C(Physics Engine)
B ==>|Depends on| D(Render Engine)
style A fill:#89c7ff,stroke:#0e3c66
style B fill:#89c7ff,stroke:#0e3c66
style C fill:#89c7ff,stroke:#0e3c66
style D fill:#89c7ff,stroke:#0e3c66
